### ISSUE TITLE
Add Google Analytics tracking to news feed

### ISSUE THREAD

**Issue by jonuy** [DoSomething/LetsDoThis-Android#146]
Inspired by https://github.com/DoSomething/LetsDoThis-iOS/issues/747 in the iOS repo.

Some things to track:
- Screen view
- clicked "Read full article"
- clicked "Take Action" button
- clicked "Share" button

**Comment by aaronschachter** [comment]
@uy - Do we need to track clicking Take Action? Wouldn't that just be tracked by the next screen loading (Campaign Detail?)

**Comment by jonuy** [comment]
@aaronschachter hm it'll definitely be tracked as a screen view and we'll be able to see that user progression through the Behavior Flow graph. So this just could be duplicating data, but I figure it's also easy enough to track the click as an event and see the data that way too. ¯\\_(ツ)_/¯
