### ISSUE TITLE
Add Optimizely Snippet to App Site

### ISSUE THREAD

**Issue by namimody** [DoSomething/LetsDoThis-Android#177]
Explainer Video: https://help.optimizely.com/hc/en-us/articles/200040095-Implement-the-Optimizely-Snippet

Snippet: `<script src="//cdn.optimizely.com/js/2090121062.js"></script>
`
Thanks!

**Comment by jonuy** [comment]
@lkpttn I think this one's meant for you?

**Comment by namimody** [comment]
Oh @jonuy sorry, I think @lkpttn moved this to the static repo. Closing!
