### ISSUE TITLE
Update the feedback Google form with the new app name

### ISSUE THREAD

**Issue by jonuy** [DoSomething/LetsDoThis-Android#182]
#### Current behavior

It currently looks like this with the "Let's Do This" app name.

![screen shot 2016-02-17 at 6 03 42 pm](https://cloud.githubusercontent.com/assets/696595/13128053/05dcf326-d5a1-11e5-8476-0af1e8df17b4.png)

#### Expected behavior

Instead of "Let's Do This", it should use "DoSomething".

cc: @marahml @lkpttn

**Comment by lkpttn** [comment]
Can you hit me up with the form link? I'll drop in new branding stuff.

**Comment by jonuy** [comment]
@lkpttn https://docs.google.com/a/dosomething.org/forms/d/1KUWQgfuoKpUXg7uuurXSgYQ3RCuxwNVSrGeb_kDRqf8/viewform
